### ISSUE TITLE
seems broken

### ISSUE THREAD

**Issue by stevenwfoley** [schleuss/certbot_dns_freedns#1]
This does not seem to be functioning. This script never actually creates the txt records but it also does not produce errors. As a comparison, I have Posh-ACME on the same machine using the same data, credentials, etc, and that creates the txt records as expected.

Below is the verbose output:

Performing the following challenges:
dns-01 challenge for [redacted]
dns-01 challenge for [redacted]
creating freedns client
logging in
domain found: [redacted] with id: [redacted]
using record_name: _acme-challenge from original: _acme-challenge.[redacted]
insert new txt record
insert with data: ('[redacted]', '_acme-challenge', '[redacted]', 60)
creating freedns client
logging in
domain found: [redacted] with id: [redacted]
using record_name: _acme-challenge from original: _acme-challenge.[redacted]
insert new txt record
insert with data: ('[redacted]', '_acme-challenge', '[redacted]', 60)
Notifying user: Waiting 120 seconds for DNS changes to propagate
Waiting 120 seconds for DNS changes to propagate

**Comment by stevenwfoley** [comment]
Found the issue. The error text of the response html is this: "You must be a subscriber to modify the TTL value". So you must pay into a membership to supply a TTL for host records. Looking at other programming language based freedns acme/certbot scripts and I don't find anyone specifying the TTL. I modified my local copy of this script to remove the TTL and it works as expected, What do you think about removing TTL from your script hosted here so it can make into ppi and docker images? TTL seems unnecessary with cleanup.

**Comment by dogesking** [comment]
@stevenwfoley where did you find the TTL in your copy, exactly ? Haven't tested the certbot just yet but I can guess that I'll have the same issue you had.

**Comment by stevenwfoley** [comment]
I submitted a pull request for this, so you can see the proposed code changes to remove the TTL.
[https://github.com/schleuss/certbot_dns_freedns/pull/2/files](https://github.com/schleuss/certbot_dns_freedns/pull/2/files)
